In [ ]:
import pandas as pd

print(pd.__version__) #displays the installed version.

2.3.3

> Pandas: is a Python library used to manipulate, analyze, clean, and organize structured data.
Think of it as a tool for working with data in tables, similar to Excel spreadsheets or SQL query results, but directly in Python.
Common applications include:
- Data cleaning and handling missing values.
- Analyzing sales, employee, and customer datasets.
- Reading and processing CSV and Excel files.
- Summarizing data and calculating statistics.
- Preparing datasets for visualization and machine learning.
- Performing data-analysis tasks in entry-level interviews.



These are the two fundamental Pandas data structures.

Series: A one-dimensional labeled array, usually representing a single column of data.
DataFrame: A two-dimensional labeled table containing rows and columns.

>Series
A Series contains values and an associated index(index labels).

In [ ]:
marks = pd.Series([10,20,30])
print(marks)

0    10
1    20
2    30
dtype: int64

In [4]:
marks = pd.Series([10,20,40,30], index=["a","b","c","d"])
print(marks)

a    10
b    20
c    40
d    30
dtype: int64

In [6]:
#CREATING FROM A DICTIONARY
marks = pd.Series({
        "Adnan":10,
        "Asrar":20,
        "Saad":30
    })
print(marks)

Adnan    10
Asrar    20
Saad     30
dtype: int64

Creating from a numpy array
'''
import numpy as np
import pandas as pd

arr = np.array([10, 20, 30, 40])
series = pd.Series(arr)

series
'''

> DataFrame
A DataFrame is the primary object you'll use throughout Pandas.

In [9]:
#Create from a dictionary of lists
#Each dictionary key becomes a column name, and each list supplies the values in that column.
students = {
    "Name":["Adnan","Asrar","Saad"],
    "Age":[25,30,3],
    "Marks":[10,20,30]
}
df = pd.DataFrame(students)
print(df)

    Name  Age  Marks
0  Adnan   25     10
1  Asrar   30     20
2   Saad    3     30

In [12]:
#creating from a list of dictionaries
students = [
    {"Name":"Adnan", "Age":20},
    {"Name":"Asrar", "Age":2},
    {"Name":"Saad", "Age":0}
]
df = pd.DataFrame(students)
df

    Name  Age
0  Adnan   20
1  Asrar    2
2   Saad    0

In [13]:
#Create form a numoy array
import numpy as np
import pandas as pd

arr = np.array([
    [1, 85],
    [2, 90],
    [3, 78]
])

df = pd.DataFrame(
    arr,
    columns=["Student_ID", "Marks"]
)

df

   Student_ID  Marks
0           1     85
1           2     90
2           3     78

In [14]:
#Create a df with custom index
df = pd.DataFrame({
    "Name":["Adnan", "Asrar"],
    "Age":[25,30]
}, index=["a","b"])
df

    Name  Age
a  Adnan   25
b  Asrar   30

In [15]:
# underssting rows, columns, indexes, column names
df = pd.DataFrame(
    {
        "Name": ["Aman", "Sara", "Rohan"],
        "Age": [21, 22, 20],
        "Marks": [85, 90, 78]
    },
    index=["S1", "S2", "S3"]
)
df

     Name  Age  Marks
S1   Aman   21     85
S2   Sara   22     90
S3  Rohan   20     78

In [25]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [ ]:
df.index #Remember: an index is a label, not necessarily a row number. It can contain strings, dates, or other valid labels.

Index(['S1', 'S2', 'S3'], dtype='object')

> Load CSV files using pd.read_csv()
CSV stands for Comma-Separated Values. It is a common format for storing tabular data.
df = pd.read_csv("students.csv") #for relative path
df = pd.read_csv("/path/to/students.csv") #for absolute path

In [26]:
#Suppose you have a file named students.csv in the same folder as your notebook:
df = pd.read_csv("students.csv")
df

    Name  Age  Marks
0   Aman   21     85
1   Sara   22     90
2  Rohan   20     78

In [27]:
df = pd.read_csv("students.csv",nrows=2) #this ll read only first 2 rows
df

   Name  Age  Marks
0  Aman   21     85
1  Sara   22     90

In [ ]:
df = pd.read_csv("students.csv", sep=";") #this ll find the ; in csv and use that as delimiter
df

  Name,Age,Marks
0     Aman,21,85
1     Sara,22,90
2    Rohan,20,78

In [33]:
df = pd.read_csv("students.csv", index_col=0)
df

       Age  Marks
Name
Aman    21     85
Sara    22     90
Rohan   20     78

> Load Excel files using pd.read_excel()
Pandas can also read Excel workbooks, commonly .xlsx files.

In [ ]:
df = pd.read_excel("students.xlsx") #to read an excel sheet
df = pd.read_excel("students.xlsx", sheet_name="Sheet1") #to read a specific excel sheet
df = pd.read_excel("students.xlsx", sheet_name=1) #to read a specific excel sheet using sheet number

excelFile = pd.ExcelFile("students.xlsx")
excelFile.sheet_names #to check the sheet names of the excel file
#If you get an error saying that an Excel-reading engine is missing, install openpyxl in your notebook's Python environment: pip install openpyxl

# For writing Excel files, Pandas also supports to_excel():
df.to_excel("output.xlsx", index=False)