The goal is to learn how to inspect a dataset, understand its structure, identify data types, summarize values, and detect missing data before performing any analysis.

1 Inspect rows: head(), tail(), sample()

2 Understand structure: shape, columns, index, info(), dtypes

3 Summarize data: describe(), value_counts(), nunique()

4 Detect missing values: isna(), notna()

5 Understand counting: size, shape, count()

In [ ]:
#practice dataset
#This dataset has six employee records, repeated names and departments, and some missing values (NaN). That lets us practise nearly every inspection method without creating separate datasets.

import pandas as pd

df = pd.DataFrame({
    "Name": ["Adnan", "Asrar", "Saad", "Zoya", "Adnan", "Mehak"],
    "Age": [26, 24, 22, None, 26, 23],
    "Department": ["IT", "HR", "IT", "Finance", "IT", "HR"],
    "Salary": [50000, 45000, 35000, 60000, None, 45000],
    "City": ["Srinagar", "Jammu", "Srinagar", "Delhi", None, "Jammu"]
})

df

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
1  Asrar  24.0         HR  45000.0     Jammu
2   Saad  22.0         IT  35000.0  Srinagar
3   Zoya   NaN    Finance  60000.0     Delhi
4  Adnan  26.0         IT      NaN      None
5  Mehak  23.0         HR  45000.0     Jammu

In [ ]:
df.head() #displays first 5 rows

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
1  Asrar  24.0         HR  45000.0     Jammu
2   Saad  22.0         IT  35000.0  Srinagar
3   Zoya   NaN    Finance  60000.0     Delhi
4  Adnan  26.0         IT      NaN      None

In [ ]:
df.head(3) #will display only 3 rows

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
1  Asrar  24.0         HR  45000.0     Jammu
2   Saad  22.0         IT  35000.0  Srinagar

In [ ]:
df.tail() #last 5 rows

    Name   Age Department   Salary      City
1  Asrar  24.0         HR  45000.0     Jammu
2   Saad  22.0         IT  35000.0  Srinagar
3   Zoya   NaN    Finance  60000.0     Delhi
4  Adnan  26.0         IT      NaN      None
5  Mehak  23.0         HR  45000.0     Jammu

In [6]:
df.tail(3) #last 3 rows

    Name   Age Department   Salary   City
3   Zoya   NaN    Finance  60000.0  Delhi
4  Adnan  26.0         IT      NaN   None
5  Mehak  23.0         HR  45000.0  Jammu

In [ ]:
df.sample() #return any randon row

   Name   Age Department   Salary      City
2  Saad  22.0         IT  35000.0  Srinagar

In [9]:
df.sample(3) #3 random rows

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
4  Adnan  26.0         IT      NaN      None
5  Mehak  23.0         HR  45000.0     Jammu

In [ ]:
df.sample(4, random_state=10) # You can make the random selection reproducible using random_state:

    Name   Age Department   Salary      City
2   Saad  22.0         IT  35000.0  Srinagar
5  Mehak  23.0         HR  45000.0     Jammu
0  Adnan  26.0         IT  50000.0  Srinagar
3   Zoya   NaN    Finance  60000.0     Delhi

In [53]:
df.sample(4, random_state=10)

    Name   Age Department   Salary      City
2   Saad  22.0         IT  35000.0  Srinagar
5  Mehak  23.0         HR  45000.0     Jammu
0  Adnan  26.0         IT  50000.0  Srinagar
3   Zoya   NaN    Finance  60000.0     Delhi

In [ ]:
df.shape #Number of rows and columns (a, b) a number of rows and b number of columns as a tuple

(6, 5)

In [13]:
#we can check each dimension seperately
print(df.shape[0]) #rows
print(df.shape[1]) #columns

6
5

In [14]:
df.columns #Column names

Index(['Name', 'Age', 'Department', 'Salary', 'City'], dtype='object')

In [15]:
#Convert them to a regular list if needed:
df.columns.tolist()

['Name', 'Age', 'Department', 'Salary', 'City']

#we can also change the names of our columns
df.columns = ["Employee", "Age", "Department", "Salary", "City"]

In [ ]:
df.index #Row labels 
#this is print RangeIndex(start=0, stop=6, step=1) becoz our dataset has defualt integer index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
df.index.tolist()
# NOTE: The index identifies rows. It isn't necessarily a unique employee ID unless you explicitly set it that way.

[0, 1, 2, 3, 4, 5]

In [ ]:
# info() — Dataset overview
# This is one of the most useful inspection methods. It shows:
# - Number of rows and columns.
# - Column names.
# - Non-null counts for each column.
# - Data types.
# - Memory usage.
df.info()
# Age is a float64 instead of an integer because the column contains a missing value (NaN), which commonly causes a standard integer column to be represented as floating point.
# Important: info() prints its summary and returns None. You normally run df.info() by itself rather than assigning its result to a variable.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
 4   City        5 non-null      object
dtypes: float64(2), object(3)
memory usage: 368.0+ bytes

In [ ]:
df.dtypes #Data types of columns

Name           object
Age           float64
Department     object
Salary        float64
City           object
dtype: object

In [26]:
#we can also do this
df["Salary"].dtype

dtype('float64')

In [27]:
# By default, describe() summarizes numeric columns. It provides:
# Statistic	Meaning
# count	Number of non-missing values
# mean	Average
# std	Standard deviation
# min	Minimum
# 25%	First quartile
# 50%	Median
# 75%	Third quartile
# max	Maximum

df.describe()

             Age        Salary
count   5.000000      5.000000
mean   24.200000  47000.000000
std     1.788854   9082.951062
min    22.000000  35000.000000
25%    23.000000  45000.000000
50%    24.000000  45000.000000
75%    26.000000  50000.000000
max    26.000000  60000.000000

In [ ]:
df.describe(include="all")
# summarizes non-numeric columns, where applicable. For categorical columns, you'll typically see:
# - count: Non-missing values.
# - unique: Number of distinct values.
# - top: Most frequent value.
# - freq: Frequency of the most frequent value.

         Name        Age Department        Salary      City
count       6   5.000000          6      5.000000         5
unique      5        NaN          3           NaN         3
top     Adnan        NaN         IT           NaN  Srinagar
freq        2        NaN          3           NaN         2
mean      NaN  24.200000        NaN  47000.000000       NaN
std       NaN   1.788854        NaN   9082.951062       NaN
min       NaN  22.000000        NaN  35000.000000       NaN
25%       NaN  23.000000        NaN  45000.000000       NaN
50%       NaN  24.000000        NaN  45000.000000       NaN
75%       NaN  26.000000        NaN  50000.000000       NaN
max       NaN  26.000000        NaN  60000.000000       NaN

In [29]:
# Count occurrences: value_counts()
df["Department"].value_counts()

Department
IT         3
HR         2
Finance    1
Name: count, dtype: int64

In [30]:
#By default, value_counts() excludes missing values.
df["City"].value_counts(dropna=False)

City
Srinagar    2
Jammu       2
Delhi       1
None        1
Name: count, dtype: int64

In [31]:
#Normalize to proportions
df["Department"].value_counts(normalize=True)

Department
IT         0.500000
HR         0.333333
Finance    0.166667
Name: proportion, dtype: float64

In [32]:
#to percentage
df["Department"].value_counts(normalize=True)*100

Department
IT         50.000000
HR         33.333333
Finance    16.666667
Name: proportion, dtype: float64

In [34]:
# Count distinct values: nunique()
df["City"].nunique()

3

In [35]:
df["City"].nunique(dropna=False)

4

In [ ]:
#unique() vs nunique()
print(df["City"].unique()) #returns list of distinct cities
print(df["City"].nunique()) #return number of distinct cities

['Srinagar' 'Jammu' 'Delhi' None]
3

In [ ]:
# isna() — Identify missing values
df.isna() #this return True or False for every cell/value

    Name    Age  Department  Salary   City
0  False  False       False   False  False
1  False  False       False   False  False
2  False  False       False   False  False
3  False   True       False   False  False
4  False  False       False    True   True
5  False  False       False   False  False

In [ ]:
df.isna().sum() #return number of na values in each column

Name          0
Age           1
Department    0
Salary        1
City          1
dtype: int64

In [39]:
df.isna().sum().sum() #returns total number of na in dataframe

np.int64(3)

In [ ]:
#notna() - Identify non-missing values
df.notna()

   Name    Age  Department  Salary   City
0  True   True        True    True   True
1  True   True        True    True   True
2  True   True        True    True   True
3  True  False        True    True   True
4  True   True        True   False  False
5  True   True        True    True   True

In [41]:
df.notna().sum()

Name          6
Age           5
Department    6
Salary        5
City          5
dtype: int64

In [ ]:
df[df.isna().any(axis=1)] #This returns rows containing at least one missing value.

    Name   Age Department   Salary   City
3   Zoya   NaN    Finance  60000.0  Delhi
4  Adnan  26.0         IT      NaN   None

In [51]:
# Understand shape, size and count()
print(df.shape) #Returns the number of rows and columns as a tuple: (6, 5).
print()
print(df.size) #Returns the total number of cells, including missing cells: 30.
print()
print(df.count()) #Returns the number of non-missing values in each column.

(6, 5)

30

Name          6
Age           5
Department    6
Salary        5
City          5
dtype: int64