1 Selecting columns: Single and multiple columns

2 Selecting rows and columns: loc[] and iloc[]

3 Filtering rows: Comparison operators and combined conditions

4 Advanced filtering: isin(), between(), query()

5 Sorting data: sort_values() and sort_index()

6 Unique values and dropping columns: unique() and drop()

In [83]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Adnan", "Asrar", "Saad", "Zoya", "Akash", "Mehak"],
    "Age": [26, 24, 22, None, 26, 23],
    "Department": ["IT", "HR", "IT", "Finance", "IT", "HR"],
    "Salary": [50000, 45000, 35000, 60000, np.nan, 45000],
    "City": ["Srinagar", "Jammu", "Srinagar", "Delhi", np.nan, "Jammu"]
})

df

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
1  Asrar  24.0         HR  45000.0     Jammu
2   Saad  22.0         IT  35000.0  Srinagar
3   Zoya   NaN    Finance  60000.0     Delhi
4  Akash  26.0         IT      NaN       NaN
5  Mehak  23.0         HR  45000.0     Jammu

> SELECTING COLUMNS

In [84]:
df["Name"] #Select a single column
#This returns a Series.

0    Adnan
1    Asrar
2     Saad
3     Zoya
4    Akash
5    Mehak
Name: Name, dtype: object

In [85]:
df[["Name","Age","Salary"]] #Select multiple columns
#this returns a DataFrame

    Name   Age   Salary
0  Adnan  26.0  50000.0
1  Asrar  24.0  45000.0
2   Saad  22.0  35000.0
3   Zoya   NaN  60000.0
4  Akash  26.0      NaN
5  Mehak  23.0  45000.0

df["Name"]       # returns Series
df[["Name"]]     # returns DataFrame
df[["Name", "Age"]]  # returns DataFrame

> SELECTING ROWS
using loc[] and iloc[] >>> most important selection tools in pandas

In [86]:
# loc[] — Label-based selection --- we have default indexes here i.e 0,1,2,3,4
df.loc[0] #Returns the row whose index label is 0.

Name             Adnan
Age               26.0
Department          IT
Salary         50000.0
City          Srinagar
Name: 0, dtype: object

In [87]:
df.loc[0, "Name"] #selecting a row and column

'Adnan'

In [88]:
df.loc[0:2] #multiple rows

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
1  Asrar  24.0         HR  45000.0     Jammu
2   Saad  22.0         IT  35000.0  Srinagar

In [89]:
df.loc[0:2, ["Name","Age"]] #multiple rows and columns
#NOTE: in this 0 and 2 both are included

    Name   Age
0  Adnan  26.0
1  Asrar  24.0
2   Saad  22.0

In [90]:
df.loc[0:4:2] #slicing

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
2   Saad  22.0         IT  35000.0  Srinagar
4  Akash  26.0         IT      NaN       NaN

In [91]:
df.loc[[1,2,0]] #multiple non consecituve rows

    Name   Age Department   Salary      City
1  Asrar  24.0         HR  45000.0     Jammu
2   Saad  22.0         IT  35000.0  Srinagar
0  Adnan  26.0         IT  50000.0  Srinagar

In [92]:
# iloc[] — Position-based selection
df.iloc[0] #returns ist row

Name             Adnan
Age               26.0
Department          IT
Salary         50000.0
City          Srinagar
Name: 0, dtype: object

In [93]:
df.iloc[0,0] #returns first row and column

'Adnan'

In [94]:
df.iloc[0:2] #returns multiple rows 
#NOTE: 0 is inclusive but 2 is exclusive

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
1  Asrar  24.0         HR  45000.0     Jammu

In [95]:
df.iloc[0:2, 0:3] #first 2 rows and first 3 columns

    Name   Age Department
0  Adnan  26.0         IT
1  Asrar  24.0         HR

In [96]:
df.iloc[[1,2,3],[2,1]] #non consecutive rows and columns

  Department   Age
1         HR  24.0
2         IT  22.0
3    Finance   NaN

> Filter rows using comparison operators
Filtering means selecting only the rows that satisfy a condition.

In [97]:
df[df["Salary"]>45000]
#in this df["Salary"]>45000 returns True and then outer df only keeps those rows which return True

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
3   Zoya   NaN    Finance  60000.0     Delhi

In [98]:
df[df["Age"]>25]

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
4  Akash  26.0         IT      NaN       NaN

we can use ==   >=   <=   !=   <   > for comparison 
and also &  |  ~  (AND, OR, NOT)

In [99]:
df[(df["Age"]>25) | (df["Salary"]>45000)]
# df[df["Age"] >= 23 & df["Salary"] >= 45000] # >>> incorrect

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
3   Zoya   NaN    Finance  60000.0     Delhi
4  Akash  26.0         IT      NaN       NaN

In [100]:
df[~(df["Department"] == "IT")]

    Name   Age Department   Salary   City
1  Asrar  24.0         HR  45000.0  Jammu
3   Zoya   NaN    Finance  60000.0  Delhi
5  Mehak  23.0         HR  45000.0  Jammu

> Advanced filtering: isin(), between(), and query()

isin() is convenient for matching several possible values.

between() is convenient for numeric or comparable ranges.

query() provides a readable expression-based alternative for many filtering tasks.

Boolean indexing with & and | is the most general and flexible approach.

In [101]:
#isin() — Match values from a list
df[df["Department"].isin(["IT","Finance"])]

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
2   Saad  22.0         IT  35000.0  Srinagar
3   Zoya   NaN    Finance  60000.0     Delhi
4  Akash  26.0         IT      NaN       NaN

In [102]:
df[~df["Department"].isin(["IT","Finance"])] #returns depts which are not IT and Finance

    Name   Age Department   Salary   City
1  Asrar  24.0         HR  45000.0  Jammu
5  Mehak  23.0         HR  45000.0  Jammu

In [103]:
# between() — Filter within a range
df[df["Salary"].between(40000, 50000)] #40000 and 50000 are both inclusive

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
1  Asrar  24.0         HR  45000.0     Jammu
5  Mehak  23.0         HR  45000.0     Jammu

In [104]:
# query() — Filter with an expression
df.query("Salary > 45000") #Find employees with salaries above ₹45,000:

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
3   Zoya   NaN    Finance  60000.0     Delhi

In [105]:
df.query("Department== 'IT' and Age > 25") #Find IT employees aged at least 25:

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
4  Akash  26.0         IT      NaN       NaN

In [106]:
#using a python variable in query()
min_amt = 40000
df[["Department", "Age", "Salary"]].query("Salary > @min_amt")

  Department   Age   Salary
0         IT  26.0  50000.0
1         HR  24.0  45000.0
3    Finance   NaN  60000.0
5         HR  23.0  45000.0

> Sort data using sort_values() and sort_index()

In [ ]:
# sort_values() — Sort by column values
df.sort_values("Salary") #by default sort_value() is ascending

    Name   Age Department   Salary      City
2   Saad  22.0         IT  35000.0  Srinagar
1  Asrar  24.0         HR  45000.0     Jammu
5  Mehak  23.0         HR  45000.0     Jammu
0  Adnan  26.0         IT  50000.0  Srinagar
3   Zoya   NaN    Finance  60000.0     Delhi
4  Akash  26.0         IT      NaN       NaN

In [108]:
df.sort_values("Salary", ascending=False)

    Name   Age Department   Salary      City
3   Zoya   NaN    Finance  60000.0     Delhi
0  Adnan  26.0         IT  50000.0  Srinagar
1  Asrar  24.0         HR  45000.0     Jammu
5  Mehak  23.0         HR  45000.0     Jammu
2   Saad  22.0         IT  35000.0  Srinagar
4  Akash  26.0         IT      NaN       NaN

In [110]:
df.sort_values(["Department","Salary"],ascending=[False, False])

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
2   Saad  22.0         IT  35000.0  Srinagar
4  Akash  26.0         IT      NaN       NaN
1  Asrar  24.0         HR  45000.0     Jammu
5  Mehak  23.0         HR  45000.0     Jammu
3   Zoya   NaN    Finance  60000.0     Delhi

In [115]:
# By default, missing values are placed at the end. You can change that:
df.sort_values("Salary", ascending=False,na_position="first")

    Name   Age Department   Salary      City
4  Akash  26.0         IT      NaN       NaN
3   Zoya   NaN    Finance  60000.0     Delhi
0  Adnan  26.0         IT  50000.0  Srinagar
1  Asrar  24.0         HR  45000.0     Jammu
5  Mehak  23.0         HR  45000.0     Jammu
2   Saad  22.0         IT  35000.0  Srinagar

In [116]:
# sort_index() — Sort by index labels
df.sort_index()

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
1  Asrar  24.0         HR  45000.0     Jammu
2   Saad  22.0         IT  35000.0  Srinagar
3   Zoya   NaN    Finance  60000.0     Delhi
4  Akash  26.0         IT      NaN       NaN
5  Mehak  23.0         HR  45000.0     Jammu

In [117]:
df.sort_index(ascending=False)

    Name   Age Department   Salary      City
5  Mehak  23.0         HR  45000.0     Jammu
4  Akash  26.0         IT      NaN       NaN
3   Zoya   NaN    Finance  60000.0     Delhi
2   Saad  22.0         IT  35000.0  Srinagar
1  Asrar  24.0         HR  45000.0     Jammu
0  Adnan  26.0         IT  50000.0  Srinagar

In [118]:
df.sort_index(axis=1)
# To sort columns by their column labels:

    Age      City Department   Name   Salary
0  26.0  Srinagar         IT  Adnan  50000.0
1  24.0     Jammu         HR  Asrar  45000.0
2  22.0  Srinagar         IT   Saad  35000.0
3   NaN     Delhi    Finance   Zoya  60000.0
4  26.0       NaN         IT  Akash      NaN
5  23.0     Jammu         HR  Mehak  45000.0

In [121]:
# Retrieve unique values using unique()
df["Department"].unique()

array(['IT', 'HR', 'Finance'], dtype=object)

In [ ]:
df["City"].unique() #it also return nan if there are any NULL values

array(['Srinagar', 'Jammu', 'Delhi', nan], dtype=object)

In [122]:
df["Department"].unique().tolist()

['IT', 'HR', 'Finance']

In [123]:
# Count the distinct departments:
df["Department"].nunique()

3

In [128]:
# Remove unwanted columns using drop()
df.drop(columns="Department") #this is temporary and doesnt change the actual data frame

    Name   Age   Salary      City
0  Adnan  26.0  50000.0  Srinagar
1  Asrar  24.0  45000.0     Jammu
2   Saad  22.0  35000.0  Srinagar
3   Zoya   NaN  60000.0     Delhi
4  Akash  26.0      NaN       NaN
5  Mehak  23.0  45000.0     Jammu

In [ ]:
df.drop(columns=["Department", "Age"]) #dropping multiple columns

    Name   Salary      City
0  Adnan  50000.0  Srinagar
1  Asrar  45000.0     Jammu
2   Saad  35000.0  Srinagar
3   Zoya  60000.0     Delhi
4  Akash      NaN       NaN
5  Mehak  45000.0     Jammu

In [130]:
#removing a row by index
df.drop(index=1)

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
2   Saad  22.0         IT  35000.0  Srinagar
3   Zoya   NaN    Finance  60000.0     Delhi
4  Akash  26.0         IT      NaN       NaN
5  Mehak  23.0         HR  45000.0     Jammu

In [132]:
df.drop(index=[0,2])

    Name   Age Department   Salary   City
1  Asrar  24.0         HR  45000.0  Jammu
3   Zoya   NaN    Finance  60000.0  Delhi
4  Akash  26.0         IT      NaN    NaN
5  Mehak  23.0         HR  45000.0  Jammu

In [134]:
#if we want to save the new data frame we can a variable
new_df = df.drop(columns=["City"])
new_df

    Name   Age Department   Salary
0  Adnan  26.0         IT  50000.0
1  Asrar  24.0         HR  45000.0
2   Saad  22.0         IT  35000.0
3   Zoya   NaN    Finance  60000.0
4  Akash  26.0         IT      NaN
5  Mehak  23.0         HR  45000.0