Q1. Filter and sort
Find employees in the IT department whose salary is at least 50,000. Display only Name, Salary, and City, and sort by Salary from highest to lowest.

Q2. Create a Series
Create a Series named prices from [150, 250, 350, 450] with custom index labels ['P1', 'P2', 'P3', 'P4'].

Q3. Inspect missing values
Calculate missing-value counts for every column and the total number of missing cells in df.

Q4. Read an Excel file
Write code to load the worksheet named 'Employees' from employees.xlsx into a DataFrame called employees. You only need to write the code; an actual file is not required.

Q5. Select using loc
Using loc, select rows with index labels 2 through 5 inclusive, displaying only Name and Salary.

Q6. Inspect the dataset
Print the number of rows, number of columns, all column names, and the data types of every column.

Q7. Create a DataFrame
Create a DataFrame called products from a dictionary with columns Product, Price, and Stock. Add three products of your choice.

Q8. Use isin()
Select employees whose Department is either HR or Finance. Display the complete matching rows.

Q9. Read a CSV file
Write code to load sales.csv into a DataFrame called sales.

Q10. Descriptive statistics
Generate descriptive statistics for all columns of df, including categorical columns.

Q11. Select using iloc
Use iloc to select the first four rows and the first three columns of df.

Q12. Count and find unique values
Display the unique department values, count the distinct departments, and count how many records belong to each department.

Q13. Use multiple conditions
Find employees aged 23 or older whose salary is between 40,000 and 60,000 inclusive. Use Boolean conditions with &. Missing values should not match.

Q14. Inspect rows and structure
Display the first three rows, the last two rows, a random sample of two rows, and the full df.info() summary.

Q15. Drop and compare
Create df_without_city by dropping City from df. Then print the shape of both DataFrames and explain why the original df is unchanged.

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Adnan", "Asrar", "Saad", "Zoya", "Mehak", "Adnan", "Rohan", "Sara"],
    "Age": [26, 24, 22, np.nan, 23, 26, 29, 21],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT", "Finance", "HR"],
    "Salary": [50000, 45000, 35000, 60000, np.nan, 55000, 70000, 40000],
    "City": ["Srinagar", "Jammu", "Srinagar", "Delhi", "Jammu", np.nan, "Delhi", "Srinagar"]
})

df

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
1  Asrar  24.0         HR  45000.0     Jammu
2   Saad  22.0         IT  35000.0  Srinagar
3   Zoya   NaN    Finance  60000.0     Delhi
4  Mehak  23.0         HR      NaN     Jammu
5  Adnan  26.0         IT  55000.0       NaN
6  Rohan  29.0    Finance  70000.0     Delhi
7   Sara  21.0         HR  40000.0  Srinagar

In [2]:
# Find employees in the IT department whose salary is at least 50,000. Display only Name, Salary, and City, and sort by Salary from highest to lowest.
df[["Name","Salary","City"]].query("Salary >= 50000").sort_values("Salary", ascending=False)

    Name   Salary      City
6  Rohan  70000.0     Delhi
3   Zoya  60000.0     Delhi
5  Adnan  55000.0       NaN
0  Adnan  50000.0  Srinagar

In [4]:
# Create a Series named prices from [150, 250, 350, 450] with custom index labels ['P1', 'P2', 'P3', 'P4'].
prices = pd.Series([150, 250, 350, 450], index=['P1','P2','P3','P4'])
prices

P1    150
P2    250
P3    350
P4    450
dtype: int64

In [ ]:
# Calculate missing-value counts for every column and the total number of missing cells in df.
df.isna().sum()
df.isna().sum().sum()

np.int64(3)

In [ ]:
# Write code to load the worksheet named 'Employees' from employees.xlsx into a DataFrame called employees. You only need to write the code; an actual file is not required.
employees = pd.read_excel("employees.xlsx")

In [9]:
# Using loc, select rows with index labels 2 through 5 inclusive, displaying only Name and Salary.

df.loc[2:5, ["Name","Salary"]]

    Name   Salary
2   Saad  35000.0
3   Zoya  60000.0
4  Mehak      NaN
5  Adnan  55000.0

In [10]:
# Print the number of rows, number of columns, all column names, and the data types of every column.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      object
 1   Age         7 non-null      float64
 2   Department  8 non-null      object
 3   Salary      7 non-null      float64
 4   City        7 non-null      object
dtypes: float64(2), object(3)
memory usage: 448.0+ bytes

In [11]:
# Create a DataFrame called products from a dictionary with columns Product, Price, and Stock. Add three products of your choice.
products = pd.DataFrame({
    "Products":["Pen","Pencil","Ink"],
    "Price":[20, 10, 30],
    "Stock":[200, 300, 100]
})
products

  Products  Price  Stock
0      Pen     20    200
1   Pencil     10    300
2      Ink     30    100

In [13]:
# Select employees whose Department is either HR or Finance. Display the complete matching rows.
df[df["Department"].isin(["HR", "Finance"])]

    Name   Age Department   Salary      City
1  Asrar  24.0         HR  45000.0     Jammu
3   Zoya   NaN    Finance  60000.0     Delhi
4  Mehak  23.0         HR      NaN     Jammu
6  Rohan  29.0    Finance  70000.0     Delhi
7   Sara  21.0         HR  40000.0  Srinagar

In [ ]:
# Write code to load sales.csv into a DataFrame called sales.
sales = pd.read_csv("sales.csv")

In [14]:
# Generate descriptive statistics for all columns of df, including categorical columns.
df.describe(include="all")

         Name        Age Department        Salary      City
count       8   7.000000          8      7.000000         7
unique      7        NaN          3           NaN         3
top     Adnan        NaN         IT           NaN  Srinagar
freq        2        NaN          3           NaN         3
mean      NaN  24.428571        NaN  50714.285714       NaN
std       NaN   2.760262        NaN  12051.476890       NaN
min       NaN  21.000000        NaN  35000.000000       NaN
25%       NaN  22.500000        NaN  42500.000000       NaN
50%       NaN  24.000000        NaN  50000.000000       NaN
75%       NaN  26.000000        NaN  57500.000000       NaN
max       NaN  29.000000        NaN  70000.000000       NaN

In [15]:
# Use iloc to select the first four rows and the first three columns of df.
df.iloc[0:4, 0:3]

    Name   Age Department
0  Adnan  26.0         IT
1  Asrar  24.0         HR
2   Saad  22.0         IT
3   Zoya   NaN    Finance

In [23]:
# Display the unique department values, count the distinct departments, and count how many records belong to each department.
df["Department"].unique()
df["Department"].nunique()
df["Department"].value_counts()

Department
IT         3
HR         3
Finance    2
Name: count, dtype: int64

In [25]:
# Find employees aged 23 or older whose salary is between 40,000 and 60,000 inclusive. Use Boolean conditions with &. Missing values should not match.
df[(df["Age"]>=23)&(df["Salary"].between(40000, 50000))]

    Name   Age Department   Salary      City
0  Adnan  26.0         IT  50000.0  Srinagar
1  Asrar  24.0         HR  45000.0     Jammu

In [31]:
# Display the first three rows, the last two rows, a random sample of two rows, and the full df.info() summary.
df.head(3)
df.tail(2)
df.sample(2)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      object
 1   Age         7 non-null      float64
 2   Department  8 non-null      object
 3   Salary      7 non-null      float64
 4   City        7 non-null      object
dtypes: float64(2), object(3)
memory usage: 448.0+ bytes

In [ ]:
# Create df_without_city by dropping City from df. Then print the shape of both DataFrames and explain why the original df is unchanged.
df_without_city = df.drop(columns='City')
df.shape
df_without_city.shape
#df remained unchanged as orignal because drop doesnt make changes in our dataframe but can store the modified table in a variable

(8, 4)