In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Employee": ["Ayaan", "Sara", "Rahul", "Sara", "Zoya",
                 "Ayaan", "Kabir", "Maya"],
    "Age": [25, np.nan, 30, np.nan, 28, 25,  np.nan, 35],
    "Salary": [40000, 50000, np.nan, 50000, 60000,
               40000, 45000, np.nan],
    "Department": ["IT", "HR", "IT", "HR", None, "IT", "Finance", "HR"]
})

df

  Employee   Age   Salary Department
0    Ayaan  25.0  40000.0         IT
1     Sara   NaN  50000.0         HR
2    Rahul  30.0      NaN         IT
3     Sara   NaN  50000.0         HR
4     Zoya  28.0  60000.0       None
5    Ayaan  25.0  40000.0         IT
6    Kabir   NaN  45000.0    Finance
7     Maya  35.0      NaN         HR

In [ ]:
# 1 Missing-value analysis
# Beginner
# Using df:
# - Display the number of missing values in each column.
# - Calculate the percentage of missing values in each column, rounded to two decimal places.
# - Find the total number of missing cells in the entire DataFrame.

df.isna().sum()
df.isna().mean()*100
df.isna().sum().sum()

Employee       0.0
Age           37.5
Salary        25.0
Department    12.5
dtype: float64

In [ ]:
# 2 Fill missing values intelligently
# Beginner–Intermediate
# Create a new DataFrame called df_filled in which:
# - Missing Age values are replaced with the median age.
# - Missing Salary values are replaced with the mean salary.
# - Missing Department values are replaced with "Unknown".
# - The original df must remain unchanged.
# Display df_filled.

df_filled = df.fillna({
    "Age":df["Age"].median(),
    "Salary":df["Salary"].mean(),
    "Department":"Unknown"
})

df_filled

  Employee   Age   Salary Department
0    Ayaan  25.0  40000.0         IT
1     Sara  28.0  50000.0         HR
2    Rahul  30.0  47500.0         IT
3     Sara  28.0  50000.0         HR
4     Zoya  28.0  60000.0    Unknown
5    Ayaan  25.0  40000.0         IT
6    Kabir  28.0  45000.0    Finance
7     Maya  35.0  47500.0         HR

In [13]:
# 3 Drop rows using conditions
# Intermediate
# Create a new DataFrame called df_clean that:
# - Removes rows where Age is missing.
# - Also removes rows where Salary is missing.
# - Keeps the original DataFrame unchanged.
# - Resets the index so it starts from zero.
# Display df_clean.

df_clean = df.dropna(subset=["Age", "Salary"]).reset_index(drop=True)
df_clean

  Employee   Age   Salary Department
0    Ayaan  25.0  40000.0         IT
1     Zoya  28.0  60000.0       None
2    Ayaan  25.0  40000.0         IT

In [27]:
# 4 Detect and remove duplicates
# Intermediate
# Using df:
# - Identify all rows that are duplicates based only on Employee and Salary.
# - Count how many rows are marked as duplicates using the default keep behavior.
# - Create df_unique by removing duplicates based on those two columns, keeping the last occurrence.

df.duplicated(["Employee","Salary"])
df.duplicated().sum()
df_unique = df.drop_duplicates(["Employee", "Salary"], keep="last" )
df_unique

  Employee   Age   Salary Department
2    Rahul  30.0      NaN         IT
3     Sara   NaN  50000.0         HR
4     Zoya  28.0  60000.0       None
5    Ayaan  25.0  40000.0         IT
6    Kabir   NaN  45000.0    Finance
7     Maya  35.0      NaN         HR

In [ ]:
# 5 Complete data-cleaning challenge
# Intermediate
# Create a new DataFrame called df_final that:
# 1. Fills missing Age values with the median.
# 2. Fills missing Salary values with the median.
# 3. Fills missing Department values with "Unknown".
# 4. Removes duplicate records based on Employee and Salary, keeping the first occurrence.
# 5. Resets the index.
# 6. Displays the final DataFrame and its shape using .shape.
# Important: Perform the operations in the specified order.

df_final = df.fillna({
    "Age":df["Age"].median(),
    "Salary":df["Salary"].median(),
    "Department":"Unknown"
})
df_final = df_final.drop_duplicates(["Employee","Salary"])
df_final.reset_index(drop=True)
df_final.shape

  Employee   Age   Salary Department
0    Ayaan  25.0  40000.0         IT
1     Sara  28.0  50000.0         HR
2    Rahul  30.0  47500.0         IT
3     Zoya  28.0  60000.0    Unknown
4    Kabir  28.0  45000.0    Finance
5     Maya  35.0  47500.0         HR