In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Ayaan", "Sara", "Rahul", "Zoya"],
    "Age": ["21", "25", "30", "28"],
    "Salary": ["40000", "50000", "60000", "45000"],
    "Joining_Date": ["2024-01-15", "2023-06-20",
                     "2022-09-10", "2024-03-05"],
    "Active": [True, False, True, True]
})

df

    Name Age Salary Joining_Date  Active
0  Ayaan  21  40000   2024-01-15    True
1   Sara  25  50000   2023-06-20   False
2  Rahul  30  60000   2022-09-10    True
3   Zoya  28  45000   2024-03-05    True

In [ ]:
df.dtypes #This shows the data type of every column.

Name            object
Age             object
Salary          object
Joining_Date    object
Active            bool
dtype: object

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          4 non-null      object
 1   Age           4 non-null      object
 2   Salary        4 non-null      object
 3   Joining_Date  4 non-null      object
 4   Active        4 non-null      bool
dtypes: bool(1), object(4)
memory usage: 260.0+ bytes

>Convert data types

In [6]:
# astype() — convert a column's type
# Use astype() when the existing values are already compatible with the target type.
df["Age"] = df["Age"].astype(float)
df

    Name   Age Salary Joining_Date  Active
0  Ayaan  21.0  40000   2024-01-15    True
1   Sara  25.0  50000   2023-06-20   False
2  Rahul  30.0  60000   2022-09-10    True
3   Zoya  28.0  45000   2024-03-05    True

In [ ]:
df["Salary"] = df["Salary"].astype(str)

pandas.core.series.Series

In [11]:
# pd.to_numeric() — convert values to numbers
# This is particularly useful when a column contains numeric strings or messy values.
df["Salary"] = pd.to_numeric(df["Salary"])

In [17]:
# The key advantage is the errors parameter.
numbers = pd.Series(["100", "200", "unknown","300"])
pd.to_numeric(numbers, errors="coerce")

0    100.0
1    200.0
2      NaN
3    300.0
dtype: float64

Parameter	            Behavior
errors="raise"	        Raises an error for invalid values; default
errors="coerce"	        Converts invalid values to missing values
errors="ignore"	        Legacy behavior; deprecated in recent Pandas versions

In [19]:
# pd.to_datetime() — convert strings to dates
df["Joining_Date"]= pd.to_datetime(df["Joining_Date"])
df.dtypes

Name                    object
Age                    float64
Salary                   int64
Joining_Date    datetime64[ns]
Active                    bool
dtype: object

In [20]:
#hanlding invalid values
series = pd.Series(["2025-10-01", "2026-09-23","Unknown"])
pd.to_datetime(series, errors="coerce")

0   2025-10-01
1   2026-09-23
2          NaT
dtype: datetime64[ns]

In [ ]:
#convert to a specific datettime format
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"], format='%Y-%m-%d')
df

    Name   Age  Salary Joining_Date  Active
0  Ayaan  21.0   40000   2024-01-15    True
1   Sara  25.0   50000   2023-06-20   False
2  Rahul  30.0   60000   2022-09-10    True
3   Zoya  28.0   45000   2024-03-05    True

Understand NaN, None and NaT
These represent missing or unavailable values in different contexts.
Value	                    Meaning
NaN	Not a Number;           commonly used for missing numeric data
None	                    Python's null object; Pandas recognizes it as missing in many columns
NaT	                        Missing date/time value

Important distinction: NaN, None and NaT are not interchangeable Python objects, even though Pandas recognizes them as missing in typical cases. Use isna() to test missingness rather than comparing a value directly with NaN.

In [27]:
missing_df = pd.DataFrame({
    "Score": [90, np.nan, 80],
    "Name": ["Ayaan", None, "Sara"],
    "Date": pd.to_datetime(["2024-01-01", None, "2024-03-01"])
})

missing_df
missing_df.isna().sum()

Score    1
Name     1
Date     1
dtype: int64

In [ ]:
# Rename columns using rename()
df = df.rename(columns={
    "Name":"Emp_name"
})
df
# rename() returns a new DataFrame by default. Use assignment or inplace=True if you want to retain the change.

  Emp_name   Age  Salary Joining_Date  Active
0    Ayaan  21.0   40000   2024-01-15    True
1     Sara  25.0   50000   2023-06-20   False
2    Rahul  30.0   60000   2022-09-10    True
3     Zoya  28.0   45000   2024-03-05    True

In [29]:
df.rename(columns={
    "Age":"Emp_age",
    "Salary":"Emp_sal"
}, inplace=True)
df

  Emp_name  Emp_age  Emp_sal Joining_Date  Active
0    Ayaan     21.0    40000   2024-01-15    True
1     Sara     25.0    50000   2023-06-20   False
2    Rahul     30.0    60000   2022-09-10    True
3     Zoya     28.0    45000   2024-03-05    True

In [ ]:
#we can also standardize all the columns
df.columns = df.columns.str.lower()
df.columns

Index(['emp_name', 'emp_age', 'emp_sal', 'joining_date', 'active'], dtype='object')

>Add and update columns

In [ ]:
# Add a new column
df["bonus"] = df["emp_sal"]*100

  emp_name  emp_age  emp_sal joining_date  active    bonus
0    Ayaan     21.0    40000   2024-01-15    True  4000000
1     Sara     25.0    50000   2023-06-20   False  5000000
2    Rahul     30.0    60000   2022-09-10    True  6000000
3     Zoya     28.0    45000   2024-03-05    True  4500000

Update existing values
df["country"] = "India"
this will change the whole country columns values to India

In [ ]:
#updating using loc
df["salary"] = df["salary"].astype(int)
# df["Active"] = df.loc["Salary">50000, "Active"]= True
# df

TypeError: '>' not supported between instances of 'str' and 'int'