In [138]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Adnan", "Ayaan", "Zoya", "Sara", "Rehan"],
    "Age": ["26", "22", "unknown", "24", "21"],
    "Salary": ["55000", "42000", "60000", "invalid", "35000"],
    "Join_Date": ["2024-01-15", "2023-06-10", "invalid", "2024-03-20", None],
    "City": ["Srinagar", "Bombay", "Delhi", "Bombay", "Jammu"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Temp": [101, 102, 103, 104, 105],
    "Notes": ["Good", None, "Average", "Good", "Excellent"]
})

df

    Name      Age   Salary   Join_Date      City Department  Temp      Notes
0  Adnan       26    55000  2024-01-15  Srinagar         IT   101       Good
1  Ayaan       22    42000  2023-06-10    Bombay         HR   102       None
2   Zoya  unknown    60000     invalid     Delhi         IT   103    Average
3   Sara       24  invalid  2024-03-20    Bombay    Finance   104       Good
4  Rehan       21    35000        None     Jammu         HR   105  Excellent

In [139]:
# Question 1 — Inspect and convert data types
# 1. Display the data types using dtypes and inspect the DataFrame using info().
# 2. Convert Age into numeric values, turning invalid entries into missing values.
# 3. Convert Salary into numeric values, turning invalid entries into missing values.
# 4. Convert Join_Date into datetime values, turning invalid dates into NaT.
# 5. Display the resulting DataFrame and its data types.

df.dtypes
df.info()
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")
df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      object
 2   Salary      5 non-null      object
 3   Join_Date   4 non-null      object
 4   City        5 non-null      object
 5   Department  5 non-null      object
 6   Temp        5 non-null      int64
 7   Notes       4 non-null      object
dtypes: int64(1), object(7)
memory usage: 448.0+ bytes

    Name   Age   Salary  Join_Date      City Department  Temp      Notes
0  Adnan  26.0  55000.0 2024-01-15  Srinagar         IT   101       Good
1  Ayaan  22.0  42000.0 2023-06-10    Bombay         HR   102       None
2   Zoya   NaN  60000.0        NaT     Delhi         IT   103    Average
3   Sara  24.0      NaN 2024-03-20    Bombay    Finance   104       Good
4  Rehan  21.0  35000.0        NaT     Jammu         HR   105  Excellent

In [140]:
# Question 2 — Rename and create columns
# Starting with the original DataFrame:
# 1. Rename Name to Employee_Name and Join_Date to Joining_Date.
# 2. Create a new column called Annual_Salary by multiplying the numeric salary by 12. Convert the salary to numeric first if necessary.
# 3. Create a Bonus column equal to 10% of the salary.
# 4. Display the updated DataFrame.
df.rename(columns={
    "Name":"Employee_Name",
    "Join_Date":"Joining_Date"
}, inplace=True)
df["Annual_Salary"] = (df["Salary"]).astype(float) * 12
df["Bonus"] = df["Salary"]/10
df

,Employee_Name,Age,Salary,Joining_Date,City,Department,Temp,Notes,Annual_Salary,Bonus
0,Adnan,26.0,55000.0,2024-01-15,Srinagar,IT,101,Good,660000.0,5500.0
1,Ayaan,22.0,42000.0,2023-06-10,Bombay,HR,102,None,504000.0,4200.0
2,Zoya,NaN,60000.0,NaT,Delhi,IT,103,Average,720000.0,6000.0
3,Sara,24.0,NaN,2024-03-20,Bombay,Finance,104,Good,NaN,NaN
4,Rehan,21.0,35000.0,NaT,Jammu,HR,105,Excellent,420000.0,3500.0

In [141]:
# Question 3 — Update values and remove columns
# Starting with the original DataFrame:
# 1. Replace every occurrence of "Bombay" in City with "Mumbai".
# 2. Remove the Temp and Notes columns.
# 3. Rename Department to Team.
# 4. Store the final result in a new DataFrame called clean_df, leaving the original df unchanged.
clean_df = df.copy()
df.replace({
    "Bombay":"Mumbai"
}, inplace=True)
clean_df.drop(columns=["Temp", "Notes"], inplace=True)
# clean_df
clean_df.rename(columns={
    "Department":"Team"
}, inplace = True)
clean_df

,Employee_Name,Age,Salary,Joining_Date,City,Team,Annual_Salary,Bonus
0,Adnan,26.0,55000.0,2024-01-15,Srinagar,IT,660000.0,5500.0
1,Ayaan,22.0,42000.0,2023-06-10,Bombay,HR,504000.0,4200.0
2,Zoya,NaN,60000.0,NaT,Delhi,IT,720000.0,6000.0
3,Sara,24.0,NaN,2024-03-20,Bombay,Finance,NaN,NaN
4,Rehan,21.0,35000.0,NaT,Jammu,HR,420000.0,3500.0

In [142]:
# Question 4 — Use map() and np.where()
# Starting with the original DataFrame:
# 1. Map departments using this dictionary:
# department_map = {    "IT": "Technology",    "HR": "Human Resources",    "Finance": "Accounts"}
# Store the result in a new column called Department_Name.
# 2. Convert Salary to numeric, coercing invalid values to missing.
# 3. Create a Salary_Level column:
#    - Salary greater than or equal to ₹50,000 → "High"
#    - Otherwise → "Low"
# Note: Decide how you want to handle missing salaries so they aren't incorrectly labelled "Low".
df
department_map = {"IT": "Technology",    "HR": "Human Resources",    "Finance": "Accounts"}
df["Department_Name"] = df["Department"].map(department_map)
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")
df["Salary_Level"] = np.where(df["Salary"]>= 50000, "High", "Low")
df

,Employee_Name,Age,Salary,Joining_Date,City,Department,Temp,Notes,Annual_Salary,Bonus,Department_Name,Salary_Level
0,Adnan,26.0,55000.0,2024-01-15,Srinagar,IT,101,Good,660000.0,5500.0,Technology,High
1,Ayaan,22.0,42000.0,2023-06-10,Mumbai,HR,102,None,504000.0,4200.0,Human Resources,Low
2,Zoya,NaN,60000.0,NaT,Delhi,IT,103,Average,720000.0,6000.0,Technology,High
3,Sara,24.0,NaN,2024-03-20,Mumbai,Finance,104,Good,NaN,NaN,Accounts,Low
4,Rehan,21.0,35000.0,NaT,Jammu,HR,105,Excellent,420000.0,3500.0,Human Resources,Low

In [143]:
# Question 5 — Use np.select() for multiple conditions
# Starting with the original DataFrame:
# 1. Convert Age and Salary to numeric, coercing invalid values to missing.
# 2. Create an Employee_Category column using np.select() with these rules, in this priority order:
#    - Salary greater than or equal to ₹50,000 → "High Earner"
#    - Otherwise, age less than 23 → "Young Employee"
#    - Otherwise → "Other"
# 3. Make sure missing age or salary values do not accidentally receive a misleading category.
# 4. Display the final DataFrame.
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Employee_Category"] = np.select(
    [
    df["Salary"] >= 50000,
    df["Age"] < 23
    ],
    [
        "High Earner", 
        "Young Employee"
    ],
    default = "Other")
df

,Employee_Name,Age,Salary,Joining_Date,City,Department,Temp,Notes,Annual_Salary,Bonus,Department_Name,Salary_Level,Employee_Category
0,Adnan,26.0,55000.0,2024-01-15,Srinagar,IT,101,Good,660000.0,5500.0,Technology,High,High Earner
1,Ayaan,22.0,42000.0,2023-06-10,Mumbai,HR,102,None,504000.0,4200.0,Human Resources,Low,Young Employee
2,Zoya,NaN,60000.0,NaT,Delhi,IT,103,Average,720000.0,6000.0,Technology,High,High Earner
3,Sara,24.0,NaN,2024-03-20,Mumbai,Finance,104,Good,NaN,NaN,Accounts,Low,Other
4,Rehan,21.0,35000.0,NaT,Jammu,HR,105,Excellent,420000.0,3500.0,Human Resources,Low,Young Employee

In [144]:
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

conditions = [
    df["Salary"].isna() | df["Age"].isna(),
    df["Salary"] >= 50000,
    df["Age"] < 23
]

choices = [
    "Unknown",
    "High Earner",
    "Young Employee"
]

df["Employee_Category"] = np.select(
    conditions,
    choices,
    default="Other"
)

df

,Employee_Name,Age,Salary,Joining_Date,City,Department,Temp,Notes,Annual_Salary,Bonus,Department_Name,Salary_Level,Employee_Category
0,Adnan,26.0,55000.0,2024-01-15,Srinagar,IT,101,Good,660000.0,5500.0,Technology,High,High Earner
1,Ayaan,22.0,42000.0,2023-06-10,Mumbai,HR,102,None,504000.0,4200.0,Human Resources,Low,Young Employee
2,Zoya,NaN,60000.0,NaT,Delhi,IT,103,Average,720000.0,6000.0,Technology,High,Unknown
3,Sara,24.0,NaN,2024-03-20,Mumbai,Finance,104,Good,NaN,NaN,Accounts,Low,Unknown
4,Rehan,21.0,35000.0,NaT,Jammu,HR,105,Excellent,420000.0,3500.0,Human Resources,Low,Young Employee