# Pandas Part 2 — Phase 3 Cheat Sheet
## Sorting, Ranking and DataFrame Organization

### 1. SORTING VALUES — `sort_values()`

```python
# Ascending order (smallest to largest)
df.sort_values(by="Salary")

# Descending order (largest to smallest)
df.sort_values(by="Salary", ascending=False)

# Sort by multiple columns
df.sort_values(
    by=["Department", "Salary"],
    ascending=[True, False]
)

# Save the sorted DataFrame
df = df.sort_values(by="Salary", ascending=False)

# Modify the original DataFrame directly
df.sort_values(by="Salary", inplace=True)
```

### 2. SORTING INDEX — `sort_index()`

```python
# Sort rows by index
df.sort_index()

# Descending index order
df.sort_index(ascending=False)

# Sort columns alphabetically
df.sort_index(axis=1)
```

- `axis=0`: sort rows by index (default).
- `axis=1`: sort columns by their labels.

### 3. RANKING — `rank()`

```python
# Rank lowest salary as 1
df["Rank"] = df["Salary"].rank()

# Rank highest salary as 1
df["Rank"] = df["Salary"].rank(ascending=False)

# Choose how ties are handled
df["Rank"] = df["Salary"].rank(method="average")
df["Rank"] = df["Salary"].rank(method="min")
df["Rank"] = df["Salary"].rank(method="max")
df["Rank"] = df["Salary"].rank(method="first")
df["Rank"] = df["Salary"].rank(method="dense")
```

**Ranking methods:**
- `average`: tied values receive the average rank (default).
- `min`: tied values receive the lowest rank in the tie.
- `max`: tied values receive the highest rank in the tie.
- `first`: ranks ties in their order of appearance.
- `dense`: tied values share a rank; the next distinct value gets the next consecutive rank.

### 4. TOP AND BOTTOM ROWS

```python
# Three highest salaries
df.nlargest(3, "Salary")

# Three lowest salaries
df.nsmallest(3, "Salary")

# Top three using multiple columns
df.nlargest(3, ["Salary", "Age"])
```

### 5. RESETTING THE INDEX

```python
# Reset index, retaining the old index as a column
df.reset_index()

# Reset index and discard old index
df.reset_index(drop=True)

# Save the reset index
df = df.reset_index(drop=True)
```

### 6. SETTING THE INDEX

```python
# Use Employee_ID as index
df.set_index("Employee_ID")

# Keep Employee_ID as a regular column too
df.set_index("Employee_ID", drop=False)

# Save the change
df = df.set_index("Employee_ID")
```

### 7. GROUPBY + RANKING

```python
# Rank salaries within each department
df["Department_Rank"] = (
    df.groupby("Department")["Salary"]
      .rank(ascending=False)
)

# Dense ranking within each department
df["Department_Rank"] = (
    df.groupby("Department")["Salary"]
      .rank(ascending=False, method="dense")
)

# Highest salary in each department
df.groupby("Department")["Salary"].max()

# Sort department alphabetically, salary highest first
df.sort_values(
    by=["Department", "Salary"],
    ascending=[True, False]
)
```

### 8. IMPORTANT DIFFERENCES

| Method | Purpose |
|---|---|
| `sort_values()` | Sort by column values |
| `sort_index()` | Sort by index labels |
| `rank()` | Assign ranks to values |
| `nlargest()` | Return rows with largest values |
| `nsmallest()` | Return rows with smallest values |
| `reset_index()` | Reset the index |
| `set_index()` | Set a column as the index |
| `groupby().rank()` | Rank values within groups |

### 9. KEY REMINDERS

- Sorting methods return a new DataFrame by default.
- Use assignment or `inplace=True` to retain sorting changes.
- `rank(ascending=False)` gives the largest value rank 1.
- `dense` ranking does not skip ranks after ties.
- `reset_index(drop=True)` discards old index labels.
- `groupby().rank()` calculates ranks separately for each group.
- Missing numeric values are generally excluded from ranking and receive `NaN` ranks by default.

### 10. QUICK PRACTICE PATTERNS

```python
# Highest-paid employee
df.nlargest(1, "Salary")

# Three youngest employees
df.nsmallest(3, "Age")

# Rank by performance, highest first
df["Performance_Rank"] = (
    df["Performance_Score"].rank(ascending=False, method="dense")
)

# Rank employees by salary within each department
df["Dept_Rank"] = (
    df.groupby("Department")["Salary"]
      .rank(ascending=False, method="dense")
)

# Sort by performance, highest first
df.sort_values("Performance_Score", ascending=False)

# Reset index after filtering
df = df.reset_index(drop=True)
```

In [74]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": [
        "Adnan", "Ayaan", "Zoya", "Sara", "Rehan",
        "Irfan", "Maya", "Kabir", "Hina", "Omar"
    ],
    "Department": [
        "IT", "HR", "IT", "Finance", "HR",
        "Finance", "IT", "HR", "Finance", "IT"
    ],
    "Age": [26, 22, 24, 29, 21, 32, 27, 25, 28, 23],
    "Salary": [
        55000, 42000, 60000, 60000, 35000,
        48000, 55000, 42000, 52000, 65000
    ],
    "Experience": [3, 1, 2, 5, 1, 6, 4, 2, 4, 2],
    "Performance_Score": [85, 78, 92, 88, 75, 88, 85, 80, 90, 95]
})

df.index = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

df

     Employee_ID   Name Department  Age  Salary  Experience  Performance_Score
10           101  Adnan         IT   26   55000           3                 85
20           102  Ayaan         HR   22   42000           1                 78
30           103   Zoya         IT   24   60000           2                 92
40           104   Sara    Finance   29   60000           5                 88
50           105  Rehan         HR   21   35000           1                 75
60           106  Irfan    Finance   32   48000           6                 88
70           107   Maya         IT   27   55000           4                 85
80           108  Kabir         HR   25   42000           2                 80
90           109   Hina    Finance   28   52000           4                 90
100          110   Omar         IT   23   65000           2                 95

> Sorting with sort_values()

In [75]:
# df.sort_values("Salary")
# or we can calso write
df.sort_values(by="Salary") #ascending=True is default

     Employee_ID   Name Department  Age  Salary  Experience  Performance_Score
50           105  Rehan         HR   21   35000           1                 75
20           102  Ayaan         HR   22   42000           1                 78
80           108  Kabir         HR   25   42000           2                 80
60           106  Irfan    Finance   32   48000           6                 88
90           109   Hina    Finance   28   52000           4                 90
10           101  Adnan         IT   26   55000           3                 85
70           107   Maya         IT   27   55000           4                 85
30           103   Zoya         IT   24   60000           2                 92
40           104   Sara    Finance   29   60000           5                 88
100          110   Omar         IT   23   65000           2                 95

In [76]:
df.sort_values(by="Salary", ascending=False)

     Employee_ID   Name Department  Age  Salary  Experience  Performance_Score
100          110   Omar         IT   23   65000           2                 95
30           103   Zoya         IT   24   60000           2                 92
40           104   Sara    Finance   29   60000           5                 88
10           101  Adnan         IT   26   55000           3                 85
70           107   Maya         IT   27   55000           4                 85
90           109   Hina    Finance   28   52000           4                 90
60           106  Irfan    Finance   32   48000           6                 88
20           102  Ayaan         HR   22   42000           1                 78
80           108  Kabir         HR   25   42000           2                 80
50           105  Rehan         HR   21   35000           1                 75

In [77]:
df.sort_values(by=["Salary", "Employee_ID"], ascending=[False, True])

     Employee_ID   Name Department  Age  Salary  Experience  Performance_Score
100          110   Omar         IT   23   65000           2                 95
30           103   Zoya         IT   24   60000           2                 92
40           104   Sara    Finance   29   60000           5                 88
10           101  Adnan         IT   26   55000           3                 85
70           107   Maya         IT   27   55000           4                 85
90           109   Hina    Finance   28   52000           4                 90
60           106  Irfan    Finance   32   48000           6                 88
20           102  Ayaan         HR   22   42000           1                 78
80           108  Kabir         HR   25   42000           2                 80
50           105  Rehan         HR   21   35000           1                 75

In [78]:
# Important: By default, sort_values() returns a new DataFrame. To save the result:
# df = df.sort_values("Salary")
# Or use inplace=True if you want to modify the existing DataFrame directly.

>Sorting by index with sort_index()

In [79]:
# Sort rows by index
df.sort_index()

     Employee_ID   Name Department  Age  Salary  Experience  Performance_Score
10           101  Adnan         IT   26   55000           3                 85
20           102  Ayaan         HR   22   42000           1                 78
30           103   Zoya         IT   24   60000           2                 92
40           104   Sara    Finance   29   60000           5                 88
50           105  Rehan         HR   21   35000           1                 75
60           106  Irfan    Finance   32   48000           6                 88
70           107   Maya         IT   27   55000           4                 85
80           108  Kabir         HR   25   42000           2                 80
90           109   Hina    Finance   28   52000           4                 90
100          110   Omar         IT   23   65000           2                 95

In [80]:
df.sort_index(ascending=False)

     Employee_ID   Name Department  Age  Salary  Experience  Performance_Score
100          110   Omar         IT   23   65000           2                 95
90           109   Hina    Finance   28   52000           4                 90
80           108  Kabir         HR   25   42000           2                 80
70           107   Maya         IT   27   55000           4                 85
60           106  Irfan    Finance   32   48000           6                 88
50           105  Rehan         HR   21   35000           1                 75
40           104   Sara    Finance   29   60000           5                 88
30           103   Zoya         IT   24   60000           2                 92
20           102  Ayaan         HR   22   42000           1                 78
10           101  Adnan         IT   26   55000           3                 85

In [81]:
df.sort_index(axis=1) #sort columns by name

     Age Department  Employee_ID  Experience   Name  Performance_Score  Salary
10    26         IT          101           3  Adnan                 85   55000
20    22         HR          102           1  Ayaan                 78   42000
30    24         IT          103           2   Zoya                 92   60000
40    29    Finance          104           5   Sara                 88   60000
50    21         HR          105           1  Rehan                 75   35000
60    32    Finance          106           6  Irfan                 88   48000
70    27         IT          107           4   Maya                 85   55000
80    25         HR          108           2  Kabir                 80   42000
90    28    Finance          109           4   Hina                 90   52000
100   23         IT          110           2   Omar                 95   65000

>Ranking with rank()

In [82]:
# Assign a rank to each value in a column.
# By default, the smallest value gets rank 1, and tied values receive the average of their ranks.
df["Salary_Rank"] = df["Salary"].rank()
df

,Employee_ID,Name,Department,Age,Salary,Experience,Performance_Score,Salary_Rank
10,101,Adnan,IT,26,55000,3,85,6.5
20,102,Ayaan,HR,22,42000,1,78,2.5
30,103,Zoya,IT,24,60000,2,92,8.5
40,104,Sara,Finance,29,60000,5,88,8.5
50,105,Rehan,HR,21,35000,1,75,1.0
60,106,Irfan,Finance,32,48000,6,88,4.0
70,107,Maya,IT,27,55000,4,85,6.5
80,108,Kabir,HR,25,42000,2,80,2.5
90,109,Hina,Finance,28,52000,4,90,5.0
100,110,Omar,IT,23,65000,2,95,10.0

In [83]:
df["Salary_Rank"] = df["Salary"].rank(ascending=False) #now largest values will get rank 1
df

,Employee_ID,Name,Department,Age,Salary,Experience,Performance_Score,Salary_Rank
10,101,Adnan,IT,26,55000,3,85,4.5
20,102,Ayaan,HR,22,42000,1,78,8.5
30,103,Zoya,IT,24,60000,2,92,2.5
40,104,Sara,Finance,29,60000,5,88,2.5
50,105,Rehan,HR,21,35000,1,75,10.0
60,106,Irfan,Finance,32,48000,6,88,7.0
70,107,Maya,IT,27,55000,4,85,4.5
80,108,Kabir,HR,25,42000,2,80,8.5
90,109,Hina,Finance,28,52000,4,90,6.0
100,110,Omar,IT,23,65000,2,95,1.0

In [84]:
#ranking methods
series = pd.Series([100, 100, 200, 300, 500, 400], index=["a", "b", "c", "d", "e", "f"])
series = series.rank(method="average") #default
series

a    1.5
b    1.5
c    3.0
d    4.0
e    6.0
f    5.0
dtype: float64

In [85]:
series = series.rank(method="min")
series

a    1.0
b    1.0
c    3.0
d    4.0
e    6.0
f    5.0
dtype: float64

In [86]:
series = series.rank(method="max", ascending=False)
series

a    6.0
b    6.0
c    4.0
d    3.0
e    1.0
f    2.0
dtype: float64

Method	    ---            How ties are handled
- average	---            Average of the tied ranks (default)
- min	    ---            Give all tied values the lowest rank in the group
- max	    ---            Give all tied values the highest rank in the group
- first 	---            Assign ranks according to their order of appearance
- dense 	---            Tied values share a rank; the next distinct value gets the next consecutive rank

>nlargest() and nsmallest()

In [87]:
df.nlargest(1, "Salary")

,Employee_ID,Name,Department,Age,Salary,Experience,Performance_Score,Salary_Rank
100,110,Omar,IT,23,65000,2,95,1.0

In [88]:
df.nsmallest(1, "Salary")

,Employee_ID,Name,Department,Age,Salary,Experience,Performance_Score,Salary_Rank
50,105,Rehan,HR,21,35000,1,75,10.0

In [89]:
df.nlargest(3, "Salary")

,Employee_ID,Name,Department,Age,Salary,Experience,Performance_Score,Salary_Rank
100,110,Omar,IT,23,65000,2,95,1.0
30,103,Zoya,IT,24,60000,2,92,2.5
40,104,Sara,Finance,29,60000,5,88,2.5

In [90]:
df.nlargest(4, ["Salary", "Employee_ID"]) #tie breaker

,Employee_ID,Name,Department,Age,Salary,Experience,Performance_Score,Salary_Rank
100,110,Omar,IT,23,65000,2,95,1.0
40,104,Sara,Finance,29,60000,5,88,2.5
30,103,Zoya,IT,24,60000,2,92,2.5
70,107,Maya,IT,27,55000,4,85,4.5

> Resetting and setting the index

In [91]:
df.reset_index() ## Reset index and retain old index as a column

,index,Employee_ID,Name,Department,Age,Salary,Experience,Performance_Score,Salary_Rank
0,10,101,Adnan,IT,26,55000,3,85,4.5
1,20,102,Ayaan,HR,22,42000,1,78,8.5
2,30,103,Zoya,IT,24,60000,2,92,2.5
3,40,104,Sara,Finance,29,60000,5,88,2.5
4,50,105,Rehan,HR,21,35000,1,75,10.0
5,60,106,Irfan,Finance,32,48000,6,88,7.0
6,70,107,Maya,IT,27,55000,4,85,4.5
7,80,108,Kabir,HR,25,42000,2,80,8.5
8,90,109,Hina,Finance,28,52000,4,90,6.0
9,100,110,Omar,IT,23,65000,2,95,1.0

In [92]:
# Reset index and discard old index
df.reset_index(drop=True)

,Employee_ID,Name,Department,Age,Salary,Experience,Performance_Score,Salary_Rank
0,101,Adnan,IT,26,55000,3,85,4.5
1,102,Ayaan,HR,22,42000,1,78,8.5
2,103,Zoya,IT,24,60000,2,92,2.5
3,104,Sara,Finance,29,60000,5,88,2.5
4,105,Rehan,HR,21,35000,1,75,10.0
5,106,Irfan,Finance,32,48000,6,88,7.0
6,107,Maya,IT,27,55000,4,85,4.5
7,108,Kabir,HR,25,42000,2,80,8.5
8,109,Hina,Finance,28,52000,4,90,6.0
9,110,Omar,IT,23,65000,2,95,1.0

In [93]:
df.set_index("Employee_ID") ## Make Employee_ID the index

,Name,Department,Age,Salary,Experience,Performance_Score,Salary_Rank
Employee_ID,,,,,,,
101,Adnan,IT,26,55000,3,85,4.5
102,Ayaan,HR,22,42000,1,78,8.5
103,Zoya,IT,24,60000,2,92,2.5
104,Sara,Finance,29,60000,5,88,2.5
105,Rehan,HR,21,35000,1,75,10.0
106,Irfan,Finance,32,48000,6,88,7.0
107,Maya,IT,27,55000,4,85,4.5
108,Kabir,HR,25,42000,2,80,8.5
109,Hina,Finance,28,52000,4,90,6.0
110,Omar,IT,23,65000,2,95,1.0

In [94]:
#make Employee_id the index and keep it as column as well
df.set_index("Employee_ID", drop=False)

,Employee_ID,Name,Department,Age,Salary,Experience,Performance_Score,Salary_Rank
Employee_ID,,,,,,,,
101,101,Adnan,IT,26,55000,3,85,4.5
102,102,Ayaan,HR,22,42000,1,78,8.5
103,103,Zoya,IT,24,60000,2,92,2.5
104,104,Sara,Finance,29,60000,5,88,2.5
105,105,Rehan,HR,21,35000,1,75,10.0
106,106,Irfan,Finance,32,48000,6,88,7.0
107,107,Maya,IT,27,55000,4,85,4.5
108,108,Kabir,HR,25,42000,2,80,8.5
109,109,Hina,Finance,28,52000,4,90,6.0
110,110,Omar,IT,23,65000,2,95,1.0

In [95]:
# By default, reset_index() and set_index() return new DataFrames. Assign the result or use inplace if you want to keep the changes.

> Sorting and ranking within groups

In [102]:
df["Department_Rank"]= (df.groupby("Department")["Salary"].rank(method="dense", ascending=False))
df.sort_values(["Department","Salary"], ascending=False)

,Employee_ID,Name,Department,Age,Salary,Experience,Performance_Score,Salary_Rank,Department_Rank
100,110,Omar,IT,23,65000,2,95,1.0,1.0
30,103,Zoya,IT,24,60000,2,92,2.5,2.0
10,101,Adnan,IT,26,55000,3,85,4.5,3.0
70,107,Maya,IT,27,55000,4,85,4.5,3.0
20,102,Ayaan,HR,22,42000,1,78,8.5,1.0
80,108,Kabir,HR,25,42000,2,80,8.5,1.0
50,105,Rehan,HR,21,35000,1,75,10.0,2.0
40,104,Sara,Finance,29,60000,5,88,2.5,1.0
90,109,Hina,Finance,28,52000,4,90,6.0,2.0
60,106,Irfan,Finance,32,48000,6,88,7.0,3.0

In [108]:
df.groupby("Department")["Salary"].max()

Department
Finance    60000
HR         42000
IT         65000
Name: Salary, dtype: int64