In [4]:
import pandas as pd
import numpy as np

employees = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": [
        "Adnan", "Ayaan", "Zoya", "Sara", "Rehan",
        "Irfan", "Maya", "Kabir", "Hina", "Omar"
    ],
    "Department": [
        "IT", "HR", "IT", "Finance", "HR",
        "Finance", "IT", "HR", "Finance", "IT"
    ],
    "Age": [26, 22, 24, 29, 21, 32, 27, 25, 28, 23],
    "Salary": [
        55000, 42000, 60000, 60000, 35000,
        48000, 55000, 42000, 52000, 65000
    ],
    "Experience": [3, 1, 2, 5, 1, 6, 4, 2, 4, 2],
    "Performance_Score": [85, 78, 92, 88, 75, 88, 85, 80, 90, 95]
})

employees.index = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

employees

     Employee_ID   Name Department  Age  Salary  Experience  Performance_Score
10           101  Adnan         IT   26   55000           3                 85
20           102  Ayaan         HR   22   42000           1                 78
30           103   Zoya         IT   24   60000           2                 92
40           104   Sara    Finance   29   60000           5                 88
50           105  Rehan         HR   21   35000           1                 75
60           106  Irfan    Finance   32   48000           6                 88
70           107   Maya         IT   27   55000           4                 85
80           108  Kabir         HR   25   42000           2                 80
90           109   Hina    Finance   28   52000           4                 90
100          110   Omar         IT   23   65000           2                 95

In [9]:
# Write code to:
# 1. Display employees sorted by Salary from highest to lowest.
# 2. Sort by Department alphabetically, then by Salary from highest to lowest within each department.
# 3. Display the rows sorted by index in descending order using sort_index().
employees.sort_values(by="Salary", ascending=False)
employees.sort_values(by=["Department","Salary"], ascending=[True, False])
employees.sort_index(ascending=False)

     Employee_ID   Name Department  Age  Salary  Experience  Performance_Score
100          110   Omar         IT   23   65000           2                 95
90           109   Hina    Finance   28   52000           4                 90
80           108  Kabir         HR   25   42000           2                 80
70           107   Maya         IT   27   55000           4                 85
60           106  Irfan    Finance   32   48000           6                 88
50           105  Rehan         HR   21   35000           1                 75
40           104   Sara    Finance   29   60000           5                 88
30           103   Zoya         IT   24   60000           2                 92
20           102  Ayaan         HR   22   42000           1                 78
10           101  Adnan         IT   26   55000           3                 85

In [14]:
# Using Performance_Score:
# 1. Create a column called Performance_Rank where the highest score receives rank 1.
# 2. Create another column called Dense_Rank using method="dense".
# 3. Display Name, Performance_Score, Performance_Rank, and Dense_Rank.
# Make sure tied scores are handled correctly.
employees["Performance_Rank"] = employees["Performance_Score"].rank(ascending=False)
employees["Dense_Rank"] = employees["Performance_Score"].rank(ascending=False, method="dense")
employees[["Name", "Performance_Score", "Performance_Rank", "Dense_Rank"]]

      Name  Performance_Score  Performance_Rank  Dense_Rank
10   Adnan                 85               6.5         5.0
20   Ayaan                 78               9.0         7.0
30    Zoya                 92               2.0         2.0
40    Sara                 88               4.5         4.0
50   Rehan                 75              10.0         8.0
60   Irfan                 88               4.5         4.0
70    Maya                 85               6.5         5.0
80   Kabir                 80               8.0         6.0
90    Hina                 90               3.0         3.0
100   Omar                 95               1.0         1.0

In [20]:
# Write code to:
# 1. Display the 3 employees with the highest salaries using nlargest().
# 2. Display the 3 employees with the lowest experience using nsmallest().
# 3. Display only the relevant columns in each result.
employees[["Employee_ID", "Name","Department","Salary"]].nlargest(3, "Salary")
employees[["Employee_ID", "Name","Department", "Experience"]].nsmallest(3, "Experience")

    Employee_ID   Name Department  Experience
20          102  Ayaan         HR           1
50          105  Rehan         HR           1
30          103   Zoya         IT           2

In [25]:
# Starting with employees:
# 1. Create a new DataFrame called employees_reset with a default integer index, discarding the old index labels.
# 2. Create another DataFrame called employees_indexed with Employee_ID as its index while retaining Employee_ID as a regular column.
# 3. Confirm both results by displaying them.
employees_reset = employees.reset_index(drop=True)
employees_reset
employees
employees_indexed = employees.set_index("Employee_ID", drop=False)
employees_indexed

,Employee_ID,Name,Department,Age,Salary,Experience,Performance_Score,Performance_Rank,Dense_Rank
Employee_ID,,,,,,,,,
101,101,Adnan,IT,26,55000,3,85,6.5,5.0
102,102,Ayaan,HR,22,42000,1,78,9.0,7.0
103,103,Zoya,IT,24,60000,2,92,2.0,2.0
104,104,Sara,Finance,29,60000,5,88,4.5,4.0
105,105,Rehan,HR,21,35000,1,75,10.0,8.0
106,106,Irfan,Finance,32,48000,6,88,4.5,4.0
107,107,Maya,IT,27,55000,4,85,6.5,5.0
108,108,Kabir,HR,25,42000,2,80,8.0,6.0
109,109,Hina,Finance,28,52000,4,90,3.0,3.0
110,110,Omar,IT,23,65000,2,95,1.0,1.0

In [27]:
# Create a column called Department_Rank that ranks employees by salary within each department, with the highest salary receiving rank 1.
# Then:
# 1. Use method="dense" for ties.
# 2. Display Name, Department, Salary, and Department_Rank.
# 3. Sort the final result by Department alphabetically and Department_Rank ascending.
employees["Department_Rank"] = employees.groupby("Department")["Salary"].rank(ascending=False)
employees[["Name", "Department", "Salary", "Department_Rank"]].sort_values(by=["Department", "Department_Rank"], ascending=[True, True])

      Name Department  Salary  Department_Rank
40    Sara    Finance   60000              1.0
90    Hina    Finance   52000              2.0
60   Irfan    Finance   48000              3.0
20   Ayaan         HR   42000              1.5
80   Kabir         HR   42000              1.5
50   Rehan         HR   35000              3.0
100   Omar         IT   65000              1.0
30    Zoya         IT   60000              2.0
10   Adnan         IT   55000              3.5
70    Maya         IT   55000              3.5